version: "3"

volumes:
  postgres:
  pgadmin:

networks:
  app_network:
    driver: bridge
  auth_service_network:
    driver: bridge
  pg_network:
    driver: bridge
services:
  auth_db:
    container_name: auth_database
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5441:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "auth"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - auth_service_network
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
      - "5051:443"
    depends_on:
      - auth_db
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - pg_network
